services:
  # Frontend (Next.js)
  - type: web
    name: prosperia-web
    runtime: node
    plan: free
    rootDir: apps/web
    buildCommand: "npm install --no-fund --no-audit && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          name: prosperia-api
          type: web
          property: host
      - key: NEXT_PUBLIC_API_PORT
        fromService:
          name: prosperia-api
          type: web
          property: port
      - key: NODE_VERSION
        value: 20.12.2

  # API (NestJS)
  - type: web
    name: prosperia-api
    runtime: node
    plan: free
    rootDir: apps/api
    buildCommand: "npm install --no-fund --no-audit && npm run build"
    startCommand: "node dist/main.js"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prosperia-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: prosperia-kv
          type: keyvalue
          property: connectionString
      - key: NODE_VERSION
        value: 20.12.2
      # Ensure devDependencies are available for TypeScript build (tsc, nest-cli)
      - key: NPM_CONFIG_PRODUCTION
        value: "false"

  # Background worker
  - type: worker
    name: prosperia-worker
    runtime: node
    plan: free
    rootDir: apps/worker
    buildCommand: "npm install --no-fund --no-audit && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: prosperia-kv
          type: keyvalue
          property: connectionString
      - key: NODE_VERSION
        value: 20.12.2
      - key: NPM_CONFIG_PRODUCTION
        value: "false"

  # Redis (Render Key Value)
  - type: keyvalue
    name: prosperia-kv
    plan: free
    ipAllowList: []

databases:
  - name: prosperia-db
    plan: free
