services:
  # Frontend (Next.js)
  - type: web
    name: prosperia-web
    runtime: node
    plan: free
    region: frankfurt
    rootDir: apps/web
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      # Use internal networking: expose host/port and let the app compose the URL.
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          name: prosperia-api
          type: web
          property: host
      - key: NEXT_PUBLIC_API_PORT
        fromService:
          name: prosperia-api
          type: web
          property: port

  # API (NestJS)
  - type: web
    name: prosperia-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: apps/api
    buildCommand: "npm ci && npm run build"
    startCommand: "node dist/main.js"
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prosperia-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: prosperia-kv
          type: keyvalue
          property: connectionString

  # Background worker
  - type: worker
    name: prosperia-worker
    runtime: node
    plan: free
    region: frankfurt
    rootDir: apps/worker
    buildCommand: "npm ci && npm run build"
    startCommand: "node dist/index.js"
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          name: prosperia-kv
          type: keyvalue
          property: connectionString

  # Redis (Render Key Value) — must be declared under services with type: keyvalue
  - type: keyvalue
    name: prosperia-kv
    plan: free
    region: frankfurt
    ipAllowList: []  # empty list = only internal connections

databases:
  - name: prosperia-db
    plan: free
    region: frankfurt
